// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrHDWP7YifYxpXhhBHSY1E3FJBI2Hpf_k',
    appId: '1:533111492480:android:e5f4db4974283fba5ebb65',
    messagingSenderId: '533111492480',
    projectId: 'aurora-demo-d9027',
    databaseURL: 'https://aurora-demo-d9027-default-rtdb.firebaseio.com',
    storageBucket: 'aurora-demo-d9027.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOam8inBTaoZxdhTtm0Jdl6OclrialI-Q',
    appId: '1:533111492480:ios:3bb5629f4d8ed7d95ebb65',
    messagingSenderId: '533111492480',
    projectId: 'aurora-demo-d9027',
    databaseURL: 'https://aurora-demo-d9027-default-rtdb.firebaseio.com',
    storageBucket: 'aurora-demo-d9027.firebasestorage.app',
    androidClientId: '533111492480-0bsj48i3p5kinor97p4vqp6kohfaakv9.apps.googleusercontent.com',
    iosClientId: '533111492480-k3rusevi143iq4ve5jh8oa5n02bm526o.apps.googleusercontent.com',
    iosBundleId: 'com.example.auroraV1',
  );
}
